dist: trusty
sudo: false
language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10
addons:
  apt:
    packages:
    - libpcap-dev
install: true
script:
  - ./check.bash
  - ./build.bash
  - ./test.bash
  - ./doc.bash
