dist: trusty
sudo: false
language: go
go:
  - 1.8.3
  - 1.9
addons:
  apt:
    packages:
    - libpcap-dev
    - libreadline-dev
install: true
script:
  - ./check.bash
  - ./build.bash
  - ./test.bash
  - ./doc.bash
